sudo: required

services:
  - docker

git:
  depth: 1
  quiet: true

language: go
go:
  - "1.10.x"

after_success:
  - make docker

deploy:
  provider: script
  script: make dockerdeploy
  on:
    branch: master
