sudo: required

services:
  - docker

language: go
go:
  - "1.10.x"

after_install:
  - make docker

deploy:
  provider: script
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push lburgazzoli/camel-go
  on:
    branch: master
